Cargo.lock
Cargo.toml
examples/explorer/Readme.md
src/evm/simulation.rs
tycho_simulation_py/Cargo.toml

Previously it was not possible to compile this crate without a Cargo.lock file because some downstream dependencies of foundry had new patch versions released which broke some interfaces.

fix: update revm and foundry

---

src/protocol/vm/erc20_overwrite_factory.rs

because it's unused and unnecessary.
Also remove skip for dead code check. Nothing should be dead now.

chore: ERC20OverwriteFactory - remove get_geth_overwrites

---

src/evm/engine_db_interface.rs
src/protocol/vm/engine.rs
src/protocol/vm/state.rs

Small simplification. Like this, EngineDatabaseInterface can only be implemented on those which implement the DatabaseRef trait, which makes sense for our case.

chore: Make EngineDatabaseInterface rely on DatabaseRef

---

Cargo.lock
Cargo.toml
src/protocol/vm/mod.rs
src/protocol/vm/state.rs
src/protocol/vm/state_builder.rs
src/protocol/vm/tycho_decoder.rs
src/protocol/vm/tycho_simulation_contract.rs

This PR aims to abstract away a lot of complexity that is in `VMPoolState` by using a builder pattern.
Currently, the `VMPoolState` is responsible for its own initialization. This one being quite complex, we had to tweak the `VMPoolState` struct itself. This adds a lot of unnecessary complexity and unexpected behavior.
The builder pattern helps us separating the initialisation and the execution of `VMPoolState`, making it more straightforward and simpler. For example many field were given to `VMPoolState` just for initialisation and never used after (`engine`, `trace`, ect..). Some were also `Option` but actually required at runtime (like `adapter_contract`).
The builder also allow any field to be directly given, this is useful for example if someone wants to manually create the …

feat: add a builder for `VMPoolState`

---

src/evm/protocol/vm/state.rs
src/evm/protocol/vm/state_builder.rs
src/evm/protocol/vm/tycho_decoder.rs

This is bug prone. If the user forgets to initialize the balance, we should raise an error instead.

fix: Don't use unwrap_or_default if balance not found

---

examples/explorer/data_feed/tycho.rs

As it's not ready and it's breaking the example

fix: Remove BalancerV2 from example

---

examples/explorer/data_feed/tycho.rs
src/evm/protocol/uniswap_v2/state.rs
src/evm/protocol/uniswap_v2/tycho_decoder.rs
src/evm/protocol/uniswap_v3/tycho_decoder.rs
src/evm/protocol/vm/adapter_contract.rs
src/evm/protocol/vm/erc20_token.rs
src/evm/protocol/vm/state.rs
src/evm/protocol/vm/state_builder.rs
src/evm/protocol/vm/tycho_decoder.rs
src/evm/protocol/vm/utils.rs
src/models.rs
src/protocol/models.rs

Also change the VMPoolState attributes to be Address instead of H160
TODO: (in the upcoming episodes):
- Replace ethers U256 with alloy U256 in the vm pool state
- Abstract away ERC20Token logic (this one is evm specific)
- Use alloy to encode and decode instead of ethers (in simulation contract)

feat: Change ERC20Token address to be alloy's Address instead of H160

---

src/evm/protocol/vm/state.rs

This is equivalent to `test_sequential_get_amount_outs` on the python side - the most important assertion being that the spot price does not remain the same after the first swap.

test: Sequential get_amount_out calls

---

examples/explorer/main.rs

After the recent Tycho prod update, we can point to beta endpoint again

chore: update default TYCHO_URL to point to beta environment

---

examples/explorer/main.rs
examples/explorer/utils.rs
src/lib.rs
src/utils.rs

This is needed for the quickstart example!

fix: Move load_all_tokens to simulation's utils

---

src/evm/decoder.rs

The negation here is wrong - we were filtering out tokens which were not included, meaning new tokens would never get added.

fix: Add tokens which are not already included in state guard

---

.github/workflows/tests-and-lints-template.yaml
examples/price_printer/main.rs
examples/quickstart/main.rs
src/evm/protocol/uniswap_v2/reserve_price.rs
src/utils.rs

This is necessary to run in the cluster

fix: Allow for no tls connections when getting tokens from Tycho

---

src/evm/protocol/mod.rs
src/evm/protocol/uniswap_v3/mod.rs
src/evm/protocol/uniswap_v3/state.rs
src/evm/protocol/uniswap_v3/tycho_decoder.rs
src/evm/protocol/uniswap_v4/mod.rs
src/evm/protocol/uniswap_v4/state.rs
src/evm/protocol/utils/mod.rs
src/evm/protocol/utils/uniswap/mod.rs
src/evm/protocol/utils/uniswap/tick_list.rs
src/evm/protocol/utils/uniswap/tick_math.rs

This PR implements the main state struct for Uniswap v4 simulation. 
I also started to move files from Uniswap v3 into a shared utils module that will be used by both Uniswaps (v3 and v4).

feat(uniswap_v4): Implement `UniswapV4State` struct

---

examples/price_printer/main.rs

This way, users will get a clear error message if they forgot to set `RPC_URL`. This variable isn't needed for uniswaps but Curve and Balancer are on by default so we enforce it by default.

refactor(example): early error if `RPC_URL` isn't set in `price_printer`

---

examples/price_printer/ui.rs

Previously, the quote amount remained unchanged when switching the target components. This caused issues, such as trading excessively large amounts when transitioning from a token with 18 decimals to one with 6 decimals (as in token).
This update ensures that the quote amount is correctly scaled to match the decimals of the new token when changing the target pool.

feat(price_printer): dynamically adapt the quote amount to the new decimals when switching row

---

src/evm/protocol/uniswap_v4/assets/sepolia_state_block_7239119.json
src/evm/protocol/uniswap_v4/state.rs

This test relies on a Sepolia state that was indexed with version `0.1.0` of the UniswapV4 Substreams module.

test(uniswap_v4): add a test for Uniswap V4 simulation

---

examples/price_printer/ui.rs
src/evm/decoder.rs
src/protocol/models.rs

Also implement From<ProtocolComponent> for tycho_core::dto::ProtocolComponent. This will be useful for tycho-execution
Deprecate address in ProtocolComponent. It should be id instead
(this was decided [here](https://propellerswap.slack.com/archives/C07H7S15LUV/p1738775735122579?thread_ts=1738687888.096819&cid=C07H7S15LUV))

feat: Extend ProtocolComponent to have the attributes of the core model

---

src/evm/protocol/mod.rs
src/evm/protocol/utils/mod.rs
src/evm/protocol/utils/uniswap/mod.rs

Resolves https://github.com/propeller-heads/tycho-simulation/issues/138
External users are unable to use UniswapV3::new fn properly as they do not have access to the TickList struct.

refactor: make TickList public

---

src/evm/decoder.rs
src/protocol/models.rs

This way, users can create a ProtocolComponent from scratch and don't get deprecation warnings because of address

fix: Create a ProtocolComponent::new() that doesn't depend on tycho-core

---

Cargo.lock
Cargo.toml
examples/price_printer/Readme.md
examples/quickstart/Readme.md
examples/quickstart/main.rs
src/protocol/models.rs

Refactor: Instead of looping through the top 10 pools and calculating spot prices and amount out for each block, it will return the best amount out for a token pair. The trade tokens can be defined through CLI parameters. 
Add execution to quickstart. The user can choose to simulate, execute or skip the swap. The output looks like this
````
Looking for the best swap for 1 WETH -> USDC
==================== Received block 21937897 ====================
The best swap (out of 6 possible pools) is:
protocol: "uniswap_v3"
id: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
swap: 1000000000000000000 WETH -> 2351701017 USDC
Do you want to simulate, execute or skip this swap?
Please be aware that the market might move while you make your decision. Which might lead to a revert if you've set a min …
```

feat: Refactor quickstart and add execution

---

examples/quickstart/main.rs

feat: 1% slippage check in quickstart

---

examples/quickstart/main.rs

fix: 0.25% slippage check in quickstart

---

Cargo.lock
Cargo.toml
examples/quickstart/main.rs

Corresponding execution [PR](https://github.com/propeller-heads/tycho-execution/pull/96)

chore: Update quickstart with new builder shortcut

---

examples/price_printer/ui.rs
examples/quickstart/main.rs

This PR adds the protocol name for each protocol component in the price printer example.
It also fixes a small bug in the quickstart example.

feat(price_printer): display the protocol name for each row in the table

---

examples/price_printer/ui.rs
src/evm/decoder.rs

This PR fixes two bugs: 
1. In the price printer example it fixes a bug where the amount would become 0 if there was a negative decimals difference between previous and current token in
2. In the Tycho decoder it fixes a bug where wrong insertions were made into the `contracts_map` leading to panics

fix: miscellaneous fixes in the price printer example and evm Tycho decoder

---

examples/price_printer/ui.rs

Currently if the users substract too much, it panics due to a BigUint error. This commit makes it catch errors during BigUint sub and default to 1 if the users tries to substract too much.

fix(price-printer): do not panic during amount calculation math.

---

Cargo.lock
Cargo.toml
src/evm/decoder.rs
src/evm/engine_db/mod.rs
src/evm/protocol/uniswap_v2/state.rs
src/evm/protocol/uniswap_v2/tycho_decoder.rs
src/evm/protocol/uniswap_v3/state.rs
src/evm/protocol/uniswap_v3/tycho_decoder.rs
src/evm/protocol/uniswap_v4/state.rs
src/evm/protocol/uniswap_v4/tycho_decoder.rs
src/evm/protocol/vm/state.rs
src/evm/protocol/vm/state_builder.rs
src/evm/protocol/vm/tycho_decoder.rs
src/evm/tycho_models.rs
src/models.rs
src/protocol/models.rs
src/protocol/state.rs
tests/assets/decoder/balancer_v2_delta.json
tests/assets/decoder/uniswap_v2_delta.json
tests/assets/decoder/uniswap_v2_snapshot.json
tests/assets/decoder/uniswap_v2_snapshot_broken_id.json
tests/assets/decoder/uniswap_v2_snapshot_broken_state.json
tycho_simulation_py/python/tycho_simulation_py/evm/decoders.py
tycho_simulation_py/python/tycho_simulation_py/evm/pool_state.py

For some protocols the balances used by a component is stored on a separate contract. To best cater for such components we now support using account_balances where the balance for relevant contracts is monitored and overwritten during simulation.
Decisions:
- it was decided to work towards deprecating the use 'balance_owners' and instead encourage using account balances. For backwards compatibility, support for protocols using balance_owner has been maintained.

feat: add account balance overrides 

---

.github/workflows/tests-and-lints-template.yaml

We started using pull_request_target event so forks can properly run the CI. But that leads to the checkout being on main which is obviously not helpful.
With this change we checkout the target branch before running the tests.
See this issue for more information:
https://github.com/actions/checkout/issues/518

chore: Checkout CI target branch.

---

Cargo.lock
Cargo.toml

- This update is needed to fix a slippage issue where 0.1% would be rounded to 0
- The latest tycho-execution also supports cyclical swaps, although this new feature isn't needed in the latest quickstart

feat: update tycho-execution version

---

examples/price_printer/main.rs
examples/price_printer/utils.rs

- Updated `register_exchanges` to include Uniswap exchanges for Unichain.
- Added default URL for Unichain in `get_default_url` function.

feat: add Unichain support in price printer

---

tycho_simulation_py/python/tycho_simulation_py/evm/decoders.py

This fixes a bug where we would not use component balances because the system would use empty account balances instead.

fix: filter out empty accounts balances

---

examples/quickstart/main.rs
examples/quickstart/utils.rs

- These improvements were copied over from the price printer. After this, we will be able to swap on more protocols if ethereum chain is chosen (sushiv2, pancakev2, pancakev3, balancer, ekubo). Before, we were restricting ourselves to protocols that were available on all chains.
- It also fetches the correct tycho default URL depending on chain.

refactor: improvemenets to quickstart

---

examples/price_printer/Readme.md
examples/price_printer/main.rs
src/evm/decoder.rs
src/evm/protocol/vm/state.rs

This PR fixes two bugs in the balance overwrites:
- We were using account-balances even when they were empty
- We were deleting some useful balances on updates for >2 tokens pools
Also added EkuboV2 in the price printer and updated the readme for Unichain support

fix(simulation): fix balances overwrites bugs

---

Cargo.lock
Cargo.toml
src/evm/protocol/filters.rs
src/evm/stream.rs

Simulation for these pools is not correct at the moment.
Add warning if filter is not set for uniswap_v4, balancer_v2 and curve

fix: Extend curve filter to filter out currently unsupported pools

---

examples/quickstart/main.rs

- Swap token direction to USDC → WETH
- Add token balance display and warnings when insufficient funds
- Improve console output formatting with proper spacing
- Fix streaming behavior after actions:
- Continue streaming after simulation
- Exit with clear summary after successful execution
- Continue on failed execution with error message
- Set reasonable default amount (10 USDC) for swaps

feat: check balance, swap direction

---

src/evm/protocol/filters.rs

This pool suffers from the same issue, its stETH indexed balances are wrong because we only account for transfered tokens and not rebasing. This then leads to bugs during simulations.

fix: update curve_pool_filter to exclude additional stETH bugged pool

---

.github/workflows/tests-and-lints-template.yaml
Cargo.lock
Cargo.toml
rust-toolchain.toml

This client version contains fixes for the smooth handling of delayed extractors.

fix: update tycho-client to version 0.70.5

---

examples/quickstart/main.rs

Curve was disable because of a bug in Tycho indexer. Now the bug is fixed so we can re-enable it.

chore: re-enable Curve in quickstart

---

.github/workflows/tests-and-lints-template.yaml
examples/price_printer/ui.rs

This PR improve the UX for the price-printer example. Specifically:
- Added a new functionality allowing users to input the swap amount
- Added a new line in the quote popup to display the swap direction

feat: improve price-printer ux

---

tycho_simulation_py/python/tycho_simulation_py/evm/decoders.py

Account balances include balances for all tokens held by that account, regardless of if that token is associated with the current pool being decoded. Since the python decoder reports balances in off-chain amounts, it's important that we have the token object for all balances we're processing so that we can do this conversion. Therefore, to avoid issues we should only process account balances for tokens that belong to the pool being decoded.

fix(python): Do not error on account balances for non-pool tokens

---

Cargo.lock
Cargo.toml
examples/quickstart/main.rs

This supports the new Ekubo executor with MEV resist

feat: Upgrade tycho-execution to 0.102.0

---

src/protocol/models.rs

This is just a helper function for the user to use if they want to merge Updates for RFQs within the same time window

fix: Add a merge method to Update

---

examples/price_printer/main.rs
examples/quickstart/main.rs
examples/rfq_quickstart/main.rs
src/rfq/protocols/hashflow/client.rs
src/rfq/protocols/hashflow/mod.rs
src/rfq/protocols/hashflow/models.rs
src/rfq/protocols/mod.rs

- Fetches mms from Hashflow API
- Passes them to the price levels API
- Normalizes all prices against the approved quote tokens (only to filter for TVL).
- Returns components for each token pair and mm.

feat(Hashflow): Hashflow price levels API client

---

src/evm/protocol/uniswap_v4/state.rs
src/evm/protocol/utils/uniswap/tick_list.rs

Please refer to the [task](https://propeller-heads.atlassian.net/jira/software/projects/ENG/boards/24?jql=&selectedIssue=ENG-4740).
`find_max_amount` uses exponential search: https://en.wikipedia.org/wiki/Exponential_search
Exponential search is likely much faster than binary search for our use case:
- `get_amount_out(I256::MAX)` will almost always fail, so this will waste time checking values unrealistically high.
- If you were to start binary search from 1 to 10^76, you'd need hundreds of iterations.

feat: get_limits for USV4 if no liquidity

---

examples/rfq_quickstart/main.rs
src/evm/protocol/uniswap_v4/hooks/generic_vm_hook_handler.rs
src/rfq/constants.rs
src/rfq/mod.rs
src/rfq/protocols/bebop/client.rs
src/rfq/protocols/bebop/client_builder.rs
src/rfq/protocols/bebop/tycho_decoder.rs
src/rfq/protocols/hashflow/client.rs
src/rfq/protocols/hashflow/mod.rs
src/rfq/protocols/hashflow/state.rs
src/rfq/protocols/hashflow/tycho_decoder.rs

[Task (no additional info)](https://propeller-heads.atlassian.net/browse/ENG-4749)
Additional fixes:
- In hashflow/bebop decoders, read auth from env
- Change tokens in test_hashflow_api_polling, since previously used tokens no longer found
- Add mm attribute to HashflowState (may be useful for user when debugging)

feat: Hashflow decoder

---

src/evm/decoder.rs
src/evm/protocol/filters.rs
src/evm/protocol/uniswap_v4/hooks/models.rs
src/evm/protocol/uniswap_v4/state.rs

New test: `test_get_amount_out_no_hook`
Two bugs fixed:
- We were adding when we should have been subtracting
- BalanceDelta was not being properly initialized
These results were found by comparing `test_get_amount_out_no_hook` results with those of the main branch, and logging intermediate results line-by-line. The findings showed that the result of `compute_swap_step` was the same for both branches, but the calculation differed by sign after calculating `state.amount_calculated`.
The output of `state.amount_remaining` seems to have been properly handled, resulting in 0 for both cases.
The way that BalanceDelta was being handled before gave us `.amount0` and `.amount1` results of `-436478419853848` and `-1` respectively, when we needed to construct it in a way that gave us `0` and …

fix: get_amount_out for usv4 pools w/o hooks

---

src/evm/engine_db/tycho_db.rs
src/evm/protocol/uniswap_v4/hooks/hook_handler_creator.rs

Account inserted with code set no None must use KECCAK_EMPTY. This commit adds explicit logs when this is not the case.

fix: correctly initialize external account hash

---

src/evm/engine_db/tycho_db.rs

For now substitute with empty code since this is most likely the correct solution.

fix: Log any account creation without code.

---

src/evm/decoder.rs
src/evm/engine_db/mod.rs
src/evm/engine_db/tycho_db.rs
src/evm/protocol/vm/state.rs
src/evm/protocol/vm/tycho_decoder.rs
src/evm/stream.rs
src/rfq/stream.rs
tycho_simulation_py/src/structs_py.rs

Propagate errors from PreCacheDB::update all the way up to decoding and log the full message that failed to decode. To see full messages that failed decoding set `RUST_LOG=info,tycho_simulation::evm::stream=debug`.
Additionally, this adds a temporary patch to treat AccountDeltas marked as creations without code as updates.

feat: Propagate db update errors

---

src/evm/decoder.rs
src/evm/protocol/uniswap_v4/state.rs
src/evm/protocol/vm/state.rs

- the issue stemmed from UniswapV4State. It's likely not an issue yet in EVMPoolState.
- beforeSwap relies on the block timestamp in the case of Euler. We get an arithmetic over/underflow if this is wrong. For an  example of where this is problematic in the EVault:
```
uint256 deltaT = block.timestamp - vaultCache.lastInterestAccumulatorUpdate;
<=> uint256 deltaT = 1758201863 - 1758201935;
```

fix: Update block in UniswapV4State and EVMPoolState

---

Cargo.lock
Cargo.toml
src/evm/decoder.rs
src/evm/protocol/uniswap_v4/hooks/generic_vm_hook_handler.rs
src/evm/protocol/uniswap_v4/hooks/hook_handler_creator.rs
src/evm/protocol/uniswap_v4/tycho_decoder.rs

Sometimes when the pool manager doesn’t hold many AAA tokens, simulating on a hook might fail.
Since we are simulating only on the before/after swap code directly, this assumes that the user has already transferred the funds into the pool manager. If it is a common token this is usually fine (the pool manager already has a high balance of this token), however sometimes this is not the case and we need to mock the pool managers balance for this token

fix: Solve issue with low balance tokens in pool manager 
