src/evm/token.rs, src/protocol/errors.rs, src/protocol/uniswap_v2/state.rs, src/protocol/uniswap_v3/state.rs, src/protocol/vm/adapter_contract.rs, src/protocol/vm/errors.rs, src/protocol/vm/models.rs, src/protocol/vm/state.rs, src/protocol/vm/state_builder.rs, src/protocol/vm/tycho_simulation_contract.rs, src/protocol/vm/utils.rs, src/safe_math.rs
Please refer to commit messages for more details/reasoning.
=> feat: Define better user-facing errors

examples/explorer/data_feed/tycho.rs, src/evm/account_storage.rs, src/evm/protocol/vm/constants.rs, src/evm/protocol/vm/state.rs, src/evm/protocol/vm/state_builder.rs, src/evm/protocol/vm/tycho_decoder.rs, src/evm/protocol/vm/tycho_simulation_contract.rs
Don't hardcode ADAPTER_ADDRESS, make it depend on the protocol
=> fix: Fix adapter contract hardcoded address

examples/explorer/main.rs, examples/quickstart/Readme.md, examples/quickstart/main.rs, src/models.rs, src/protocol/models.rs, src/utils.rs
Also update tycho url to point to prod
=> feat: Add Quickstart

.github/workflows/tests-and-lints-template.yaml, Readme.md, src/evm/protocol/vm/constants.rs, src/evm/protocol/vm/mod.rs, src/evm/protocol/vm/state.rs, src/evm/protocol/vm/state_builder.rs, src/evm/protocol/vm/tycho_decoder.rs, src/evm/protocol/vm/tycho_simulation_contract.rs, src/evm/protocol/vm/utils.rs
This way the bytecode is loaded at compile time and not at run time, this way we won't have problems with weird paths  (I hope)
=> fix: Load bytecode from files with include_bytes!

src/evm/protocol/uniswap_v3/state.rs, src/evm/protocol/uniswap_v3/tycho_decoder.rs, src/evm/protocol/uniswap_v4/mod.rs, src/evm/protocol/uniswap_v4/tycho_decoder.rs, src/evm/protocol/utils/uniswap/mod.rs
TODO: 
- Migrate tests
- Verify data types (e.g.: i24 -> i32)
=> feat: TryFromWithBlock impl for UniV4State

Cargo.lock, Cargo.toml, examples/price_printer/main.rs, examples/quickstart/main.rs, src/evm/tycho_models.rs, src/utils.rs
Includes:
- updating the tycho-indexer version used to one that supports Base chain
- removing unnecessary re-implementations of tycho core enums
- add chain argument to load_all_tokens instead of hardcoding it to Ethereum
=> feat: better support switching chains

examples/price_printer/main.rs, examples/quickstart/main.rs, src/utils.rs
And chain specific defaults to the activity filter
=> feat: add filter args to load_all_tokens

examples/price_printer/Readme.md, examples/price_printer/main.rs, examples/price_printer/utils.rs
This PR adds the support for Base in the `price-printer` example
=> feat(example): add Base support in the `price-printer` example

src/evm/protocol/uniswap_v4/state.rs, src/evm/protocol/uniswap_v4/tycho_decoder.rs, tests/assets/decoder/uniswap_v4_snapshot_sepolia_block_7239119.json
LP fees were moved from state attributes to static attributes.
=> feat: update uniswap v4 decoding of lp fees

examples/price_printer/main.rs, examples/price_printer/utils.rs, examples/quickstart/main.rs, src/evm/stream.rs, src/evm/tycho_models.rs, src/protocol/models.rs, src/utils.rs
Replaces dto::Chain with models::Chain
=> refactor: replace dto::Chain with models::Chain

src/evm/protocol/uniswap_v3/state.rs, src/evm/protocol/uniswap_v4/state.rs
=> ci: make clippy happy

Cargo.lock, Cargo.toml, src/evm/protocol/ekubo/pool/base.rs, src/evm/protocol/ekubo/pool/full_range.rs, src/evm/protocol/ekubo/pool/mod.rs, src/evm/protocol/ekubo/pool/oracle.rs, src/evm/protocol/ekubo/state.rs, src/evm/protocol/ekubo/test_pool.rs, src/evm/protocol/ekubo/tycho_decoder.rs
This mainly fixes an issue with valid pool constructor arguments being rejected (see https://github.com/EkuboProtocol/evm-rust-sdk/commit/01b2fb4237e481c468325c89289229aa6700ceea)
=> fix: Upgrade Ekubo Rust SDK to v0.4.0

Cargo.lock, Cargo.toml, examples/quickstart/main.rs
- We no longer pass router address in the Solution object
=> feat: update tycho-execution version

examples/quickstart/Readme.md, examples/quickstart/main.rs
- This makes it easier for users to use out-of-the-box.
=> feat: default tokens per chain in quickstart

src/evm/protocol/filters.rs
- remove excessive logging
- set all filter logs to debug log level
- add doc strings for all filters
=> refactor: improve protocol filter logs

src/evm/protocol/uniswap_v3/state.rs, src/evm/protocol/uniswap_v4/state.rs, src/evm/protocol/utils/uniswap/liquidity_math.rs
Closes issue https://github.com/propeller-heads/tycho-simulation/issues/141
=> fix(uniswap): do not panic in add_liquidity_delta util function

CHANGELOG.md, Cargo.lock, Cargo.toml, src/evm/protocol/uniswap_v4/hooks/mod.rs, src/evm/protocol/uniswap_v4/mod.rs, src/evm/protocol/uniswap_v4/state.rs, tycho_simulation_py/Cargo.toml, tycho_simulation_py/pyproject.toml
[Task](https://propeller-heads.atlassian.net/browse/ENG-4570)
=> feat(UniswapV4State): Add hook attr and setter

src/evm/protocol/uniswap_v4/hooks/mod.rs, src/evm/protocol/uniswap_v4/hooks/utils.rs
[Issue](https://propeller-heads.atlassian.net/browse/ENG-4573)
Tests taken from here: https://github.com/shuhuiluo/uniswap-v4-sdk-rs/blob/main/src/utils/hook.rs#L93
=> feat: Implement has_permission for hooks

Cargo.lock, Cargo.toml, src/evm/decoder.rs, src/evm/engine_db/mod.rs, src/evm/protocol/ekubo/tycho_decoder.rs, src/evm/protocol/pancakeswap_v2/tycho_decoder.rs, src/evm/protocol/uniswap_v2/tycho_decoder.rs, src/evm/protocol/uniswap_v3/tycho_decoder.rs, src/evm/protocol/uniswap_v4/tycho_decoder.rs, src/evm/protocol/vm/tycho_decoder.rs, src/evm/stream.rs, src/protocol/models.rs, src/rfq/client.rs, src/rfq/errors.rs, src/rfq/mod.rs, src/rfq/models.rs, src/rfq/stream.rs
[Task](https://propeller-heads.atlassian.net/jira/software/projects/ENG/boards/24?selectedIssue=ENG-4689)
Review by commit for more info
Related PR: https://github.com/propeller-heads/tycho-indexer/pull/624
=> feat: Implement RFQStreamBuilder 

src/rfq/protocols/bebop/models.rs, src/rfq/protocols/bebop/state.rs
Refactor get_price to extract get_amount_out_from_levels logic out
=> feat(Bebop): Implement get_amount_out

src/evm/protocol/vm/state.rs
This commit fixes a bug where we were completely replacing the pool state.balances on updates. For >2 tokens pool it was leading to some balances being lost. Specifically, if the state.balances was holding balances for 3 tokens and the update was only affecting 2 of them, we were deleting the 3rd token's balance from the pool state. We are now just inserting the new balances but we keep the unchanged ones.
=> fix: correctly insert balances updates

src/evm/decoder.rs, src/evm/protocol/cpmm/protocol.rs, src/evm/protocol/ekubo/tycho_decoder.rs, src/evm/protocol/pancakeswap_v2/tycho_decoder.rs, src/evm/protocol/uniswap_v2/tycho_decoder.rs, src/evm/protocol/uniswap_v3/state.rs, src/evm/protocol/uniswap_v3/tycho_decoder.rs, src/evm/protocol/uniswap_v4/state.rs, src/evm/protocol/uniswap_v4/tycho_decoder.rs, src/evm/protocol/vm/tycho_decoder.rs, src/protocol/models.rs, src/rfq/protocols/bebop/mod.rs, src/rfq/protocols/bebop/tycho_decoder.rs, src/rfq/stream.rs
[Issue](https://propeller-heads.atlassian.net/browse/ENG-4693)
=> feat: Bebop Decoder

src/evm/decoder.rs, src/protocol/models.rs
Forwards the clients state synchronization information to the Update message.
=> feat: Exposes state synchronization info on Update struct.

src/rfq/protocols/bebop/client.rs, src/rfq/protocols/bebop/models.rs
[task](https://propeller-heads.atlassian.net/jira/software/projects/ENG/boards/24?selectedIssue=ENG-4791)
=> feat(Bebop): Support AggregateOrders when requesting the quote

src/evm/stream.rs
This informs our users exactly about the behaviour of the stream and allows them to structure their applications respectively.
=> docs: Document stream module.
